### ISSUE TITLE
Installation on pre-lollipop

### ISSUE THREAD

**Issue by ghost1372** [googlesamples/android-topeka#31] opened 2015-09-15 07:31 UTC
Hi,
The application can not be installed on Android 5 down
I have Android 4.4 and 4, but the program is not installed
Please solve this problem.

**Comment by keyboardsurfer** [comment] 2015-09-15 10:30
Duplicate of #14.

**Comment by ghost1372** [comment] 2015-09-15 16:06
When we can use pre-lolipop?
I strongly need it.
tnx

**Comment by keyboardsurfer** [comment] 2015-09-15 17:04
Let's keep the communication on the bug mentioned above. Closing this one.

**Closed by keyboardsurfer** 2015-09-15 17:04 UTC

**Comment by keyboardsurfer** [comment] 2015-10-13 16:40
Fixed with the latest release.
