### ISSUE TITLE
DataBindingUtil ActivityCategorySelectionBinding not found

### ISSUE THREAD

**Issue by jsmhy** [googlesamples/android-topeka#95] opened 2017-05-25 04:06 UTC
That's my issues:
Error:(23, 27) error: package android.databinding not found
Error:(40, 50) error: package com.google.samples.apps.topeka.databinding not found
Error:(71, 9) error: not found
符号:   class ActivityCategorySelectionBinding
位置: class CategorySelectionActivity
Error:(71, 52) error: not found
符号:   变量 DataBindingUtil
位置: class CategorySelectionActivity

**Comment by keyboardsurfer** [comment] 2017-05-25 15:20
Try to clear the build cache and build again.
Let me know if the issue persists.

**Comment by keyboardsurfer** [comment] 2017-06-19 09:56
Closing this issue. Please re-open and add further context if the problem persists.

**Closed by keyboardsurfer** 2017-06-19 09:56 UTC

**Comment by keyboardsurfer** [comment] 2019-01-21 16:06
From a completely clean clone & build I can not reproduce the issue. Please advise on how the issue came to light.

**Comment by keyboardsurfer** [comment] 2019-01-21 16:06
From a completely clean clone & build I can not reproduce the issue. Please advise on how the issue came to light.

**Comment by IAmNirmesh** [comment] 2019-01-21 16:11
Followed till Step 5 [https://codelabs.developers.google.com/codelabs/android-instant-apps/index.html?index#4](url)
**And then Build -> Clean Project
Then Build -> Rebuild Project**

And the screen is there then :(

**PS: I'm downloading the source code and importing it manually.**

**Comment by IAmNirmesh** [comment] 2019-01-21 16:14
By the way, you are having **targetSdkVersion 27** originally while when I'm creating the installed module, it is **targetSdkVersion 28**
Do you think this might be the issue?

**Comment by IAmNirmesh** [comment] 2019-01-21 16:53
@keyboardsurfer ??

**Comment by keyboardsurfer** [comment] 2019-01-22 13:14
Thanks to your comments I realized that this is an issue in [the instant apps codelab](github.com/googlecodelabs/android-topeka).

There's a note that reads: 

> Note that because you are changing around gradle build files, your app won't and shouldn't be able to build in the middle of these steps. Don't worry if you see errors and wait until you're instructed to sync your app with Gradle.

Have you finished the step?

I recommend not making changes to sdk versions while performing the refactoring even though I don't see an immediate issue with this at the moment.

**Comment by IAmNirmesh** [comment] 2019-01-22 13:39
@keyboardsurfer I am still at Step 5. And according to the tutorial, it says to build the installed app and it should run exactly the same way it is suppose to be. But since I'm facing these errors, I'm not able to build it.
Please suggest.

**PS: in the tutorial, you are using the Kotlin version while I'm using the Java code. Hope that should not be a cause of this issue either, right?**

**Comment by keyboardsurfer** [comment] 2019-01-22 13:44
So you're kind of following along the codelab but introduced your own deviations from it?
I can't really help out in that case. We made adjustments in order to assure that the codelab builds at every stage. On a different codebase you might encounter issues which we haven't anticipated.
